apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: avwalgelp-go 
  janus-idp.io/tekton: avwalgelp-go
  backstage.io/kubernetes-id: avwalgelp-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: avwalgelp-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml